### ISSUE TITLE
Can't locate Module/Build.pm

### ISSUE THREAD

**Issue by Kreijstal** [duncs/clusterssh#105]
downloading this project and then executing `perl ./Build.PL` gives 
Can't locate Module/Build.pm in @INC (you may need to install the Module::Build module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./Build.PL line 5.
BEGIN failed--compilation aborted at ./Build.PL line 5.

**Comment by blackbat24** [comment]
Same issue on Master branch and perl version v5.22.1

**Comment by duncs** [comment]
Does `perl ./Makefile.PL` also fail?

**Comment by blackbat24** [comment]
I know nothing of perl, so forgive me if I make any stupid mistakes.

I ran:
`perl ./Makefile`

Which seemed to work:

> Checking if your kit is complete...
> Looks good
> Warning: prerequisite CPAN::Changes 0.27 not found.
> Warning: prerequisite File::Slurp 0 not found.
> Warning: prerequisite File::Which 0 not found.
> Warning: prerequisite Perl::Tidy 20180220 not found.
> Warning: prerequisite Readonly 0 not found.
> Warning: prerequisite Test::Differences 0 not found.
> Warning: prerequisite Test::DistManifest 0 not found.
> Warning: prerequisite Test::PerlTidy 0 not found.
> Warning: prerequisite Test::Pod 0 not found.
> Warning: prerequisite Test::Pod::Coverage 0 not found.
> Warning: prerequisite Test::Trap 0 not found.
> Warning: prerequisite X11::Protocol::WM 0 not found.
> Generating a Unix-style Makefile
> Writing Makefile for App::ClusterSSH                             
> Writing MYMETA.yml and MYMETA.json

I then tried `sudo make install`, which resulted in:

> cp bin/cssh blib/script/cssh
> "/usr/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/cssh
> "/usr/bin/perl" "-Iblib/arch" "-Iblib/lib" bin_PL/_build_docs bin/clusterssh_bash_completion.dist
> Using perl binary: /usr/bin/perl
> Using perl version v5.22.1
> Generating: /home/rfapostolo/github/clusterssh/bin_PL/clusterssh_bash_completion.dist
> cp bin/clusterssh_bash_completion.dist blib/script/clusterssh_bash_completion.dist
> "/usr/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/clusterssh_bash_completion.dist
> "/usr/bin/perl" "-Iblib/arch" "-Iblib/lib" bin_PL/_build_docs bin/crsh
> Using perl binary: /usr/bin/perl
> Using perl version v5.22.1
> Generating: /home/rfapostolo/github/clusterssh/bin_PL/crsh
> Can't locate X11/Protocol/WM.pm in @INC (you may need to install the X11::Protocol::WM module) (@INC contains: /home/rfapostolo/github/clusterssh/bin_PL/../lib/perl5 home/rfapostolo/github/clusterssh/bin_PL/../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/rfapostolo/github/clusterssh/bin_PL/../lib/App/ClusterSSH/Window/Tk.pm line 23.
> BEGIN failed--compilation aborted at home/rfapostolo/github/clusterssh/bin_PL/../lib/App/ClusterSSH/Window/Tk.pm line 23.
> Compilation failed in require at home/rfapostolo/github/clusterssh/bin_PL/../lib/App/ClusterSSH/Window.pm line 23.
> BEGIN failed--compilation aborted at home/rfapostolo/github/clusterssh/bin_PL/../lib/App/ClusterSSH.pm line 16.
> Compilation failed in require at /home/rfapostolo/github/clusterssh/bin_PL/crsh line 8.
> BEGIN failed--compilation aborted at /home/rfapostolo/github/clusterssh/bin_PL/crsh line 8.
> Failed to generate pod at bin_PL/_build_docs line 39.
> Makefile:532: recipe for target 'bin/crsh' failed
> make: *** [bin/crsh] Error 2

Am I missing a package, or just doing it wrong?

**Comment by blackbat24** [comment]
Hi again.

I had completely missed that there was an Ubuntu package. It installs and works flawlessly. Thank you very much for your help and your work!
