### ISSUE TITLE
cssh fails to start if there are multiple entries in xauth

### ISSUE THREAD

**Issue by etam** [duncs/clusterssh#120]
clusterssh version: 4.13.2.02
It failed to start with the following error:
```
$ cssh some_server
Connection to server failed -- (version 11.0)
Invalid MIT-MAGIC-COOKIE-1 key at /usr/lib/perl5/vendor_perl/5.28.1/App/ClusterSSH/Window/Tk.pm line 54.
```
The problem for cssh was that xauth had multiple entries:
```
$ xauth list
localhost/unix:0  MIT-MAGIC-COOKIE-1  <some_hash>
etam-komp/unix:0  MIT-MAGIC-COOKIE-1  <some_other_hash>
etam-komp.lan.golem.network/unix:0  MIT-MAGIC-COOKIE-1  <some_completely_different_hash>
$ env | grep XAUTH
XAUTHORITY=/home/etam/.Xauthority
XAUTHLOCALHOSTNAME=etam-komp.lan.golem.network
```
After I deleted `localhost/unix:0` and `etam-komp/unix:0` from xauth, cssh started properly.

**Comment by duncs** [comment]
This is a Tk issue as I do not do anything directly with X auth within this tool

**Comment by jirib** [comment]
I got the same on latest openSUSE Tumbleweed (*clusterssh-4.16-1.5.noarch*). Any idea how to solve this?
