### ISSUE TITLE
test t/boilerplate.t fails on Fedora 31+

### ISSUE THREAD

**Issue by rosset** [duncs/clusterssh#122]
I saw there are some commits in master that perhaps fix this issue, maybe it's time to release a new version?

Thanks.

+ ./Build test
couldn't open README for reading: No such file or directory at t/boilerplate.t line 9.
# Looks like your test exited with 2 before it could output anything.
Failed 1/13 test programs. 0/1967 subtests failed.
error: Bad exit status from /var/tmp/rpm-tmp.x5w5ve (%check)
t/00-load.t ....... ok
t/01l10n.t ........ ok
t/02base.t ........ ok
t/05getopts.t ..... ok
t/10host.t ........ ok
t/15config.t ...... ok
t/20helper.t ...... ok
t/30cluster.t ..... ok
t/80clusterssh.t .. ok
t/boilerplate.t ...
Dubious, test returned 2 (wstat 512, 0x200)
Failed 3/3 subtests
t/pod-coverage.t .. ok
t/pod.t ........... ok
t/range.t ......... ok

Test Summary Report
-------------------
t/05getopts.t   (Wstat: 0 Tests: 175 Failed: 0)
  TODO passed:   160-163, 168-171
t/boilerplate.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
Files=13, Tests=1967,  7 wallclock secs ( 0.39 usr  0.06 sys +  6.67 cusr  0.71 csys =  7.83 CPU)
Result: FAIL

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.x5w5ve (%check)
Could not execute local: rpmbuild --define '_sourcedir /home/filiperosset/rpmbuild/my/clusterssh' --define '_specdir /home/filiperosset/rpmbuild/my/clusterssh' --define '_builddir /home/filiperosset/rpmbuild/my/clusterssh' --define '_srcrpmdir /home/filiperosset/rpmbuild/my/clusterssh' --define '_rpmdir /home/filiperosset/rpmbuild/my/clusterssh' --define 'dist %{?distprefix}.fc32' --define 'fedora 32' --eval '%undefine rhel' --define 'fc32 1' -ba /home/filiperosset/rpmbuild/my/clusterssh/clusterssh.spec | tee .build-4.13.2_02-1.fc32.log
[filiperosset@raw clusterssh]$

**Comment by duncs** [comment]
I've just pushed 4.14 to cpan
