### ISSUE TITLE
Can't copy content from a cssh window

### ISSUE THREAD

**Issue by kellerman-mota** [duncs/clusterssh#124]
Hi.
Which command or shortcut is used to copy a content from a cssh window? 
I tried ctrl+c and ctrl+shit+c but there's nothing to paste.

I'm using the version 4.05

**Comment by pevik** [comment]
I use to for copy (both from and to) standard linux way to copy: the middle mouse button.

**Comment by cqexbesd** [comment]
Copy and paste isn’t implemented by cssh but by your X Windows setup and/or the terminal app you are using (I forget exactly how it’s done). As @pevik said the normal way under X Windows is hilight with the mouse to copy and middle mouse button to paste. If this doesn’t work in your environment then I’m not sure why but he solution is unlikely to be found with cssh.

**Comment by cqexbesd** [comment]
I’m surprised ^c copies in whatever terminal you are using - but whatever works for you...

Anyway whatever setting you need will be in either the terminal app you are using with cssh (xterm by default) or in your desktop environment. It don’t expect there will be anything in cssh that can fix this for you.

Does copy and paste work in a single xterm without cssh? If not then you have a good test case and maybe you can try a Linux Mint forum. Does middle mouse button ever work to paste in your environment? That might be a good data point as well. I’m afraid I have no experience with Linux Mint so I can’t give you anything more specific.

**Comment by kellerman-mota** [comment]
ok @cqexbesd 
Thanks for the feedback
