### ISSUE TITLE
Unable to build on cygwin windows 10

### ISSUE THREAD

**Issue by sanjay92-gupta** [duncs/clusterssh#125]
$ perl Build.PL 
Checking prerequisites...
  build_requires:
    !  Test::PerlTidy is not installed

I have installed cpan Test::PerlTidy but issue remains same

**Comment by sanjay92-gupta** [comment]
with 4.14 version
 ~/clusterssh

$ perl Build.PL
Could not get valid metadata. Error is: ERROR: Missing required field 'dist_abstract' for metafile

Could not create MYMETA files
Creating new 'Build' script for 'App-ClusterSSH' version '4.14'

**Comment by duncs** [comment]
Can you confirm which version of cygwin you have installed along with the version of perl?  Are all your perl libraries up to date?  The errors you have shown here suggests you have older versions installed.

There are a number of prereq's available within cygwin itself (such as https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fperl-XML-Simple%2Fperl-XML-Simple-2.25-1).  For anything else you should be able to install and use cpanminus (https://metacpan.org/pod/App::cpanminus) which will build all the required prereq's for you (assuming you are using the cygwin shell rather than a standard windows command terminal)

**Comment by duncs** [comment]
for reference: https://bennierobinson.com/programming/2016/01/24/perl-windows-2016.html#cpanminus

**Comment by sanjay92-gupta** [comment]
$ perl -V
Summary of my perl5 (revision 5 version 26 subversion 3) configuration:

  Platform:
    osname=cygwin
    osvers=3.0.7(0.33853)
    archname=x86_64-cygwin-threads-multi
    uname='cygwin_nt-10.0 cygwinpro 3.0.7(0.33853) 2019-04-30 18:08 x86_64 cygwin '
    config_args='-des -Dprefix=/usr -Dmksymlinks -Darchname=x86_64-cygwin-threads -Dlibperl=cygperl5_26.dll -Dcc=gcc -Dld=g++ -Accflags=-ggdb -O2 -pipe -Wall -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/build=/usr/src/debug/perl-5.26.3-2 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/src/perl-5.26.3=/usr/src/debug/perl-5.26.3-2 -fwrapv'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -ggdb -O2 -pipe -Wall -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/build=/usr/src/debug/perl-5.26.3-2 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/src/perl-5.26.3=/usr/src/debug/perl-5.26.3-2 -fwrapv -fno-strict-aliasing'
    optimize='-O3'
    cppflags='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -ggdb -O2 -pipe -Wall -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/build=/usr/src/debug/perl-5.26.3-2 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/src/perl-5.26.3=/usr/src/debug/perl-5.26.3-2 -fwrapv -fno-strict-aliasing'
    ccversion=''
    gccversion='7.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags =' -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'
    libpth=/usr/lib
    libs=-lpthread -lnsl -lgdbm -ldb -ldl -lcrypt -lgdbm_compat
    perllibs=-lpthread -lnsl -ldl -lcrypt
    libc=/usr/lib/libcygwin.a
    so=dll
    useshrplib=true
    libperl=cygperl5_26.dll
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
  Locally applied patches:
    Cygwin: README
    Cygwin: use auto-image-base instead of fixed DLL base address
    Cygwin: modify hints
    Cygwin: Configure correct libsearch
    Cygwin: Configure correct libpth
    Cygwin: Win32 correct UTF8 handling
    Perl: File-Path-2.14 (fixes CVE2017-6512)
  Built under cygwin
  Compiled at Aug 24 2019 12:22:19
  %ENV:
    PERL5LIB="/home/gusa7001/perl5/lib/perl5"
    PERL_LOCAL_LIB_ROOT="/home/gusa7001/perl5"
    PERL_MB_OPT="--install_base "/home/gusa7001/perl5""
    PERL_MM_OPT="INSTALL_BASE=/home/gusa7001/perl5"
  @INC:
    /home/gusa7001/perl5/lib/perl5/5.26.3/x86_64-cygwin-threads-multi
    /home/gusa7001/perl5/lib/perl5/5.26.3
    /home/gusa7001/perl5/lib/perl5/x86_64-cygwin-threads-multi
    /home/gusa7001/perl5/lib/perl5
    /usr/local/lib/perl5/site_perl/5.26/x86_64-cygwin-threads
    /usr/local/share/perl5/site_perl/5.26
    /usr/lib/perl5/vendor_perl/5.26/x86_64-cygwin-threads
    /usr/share/perl5/vendor_perl/5.26
    /usr/lib/perl5/5.26/x86_64-cygwin-threads
    /usr/share/perl5/5.26

 ~
$ uname -r
3.1.2(0.340/5/3)
