### ISSUE TITLE
How to install on CentOS 8?

### ISSUE THREAD

**Issue by da0ist** [duncs/clusterssh#126]
I've tried cpanm, cpan and manual install all to no avail. What's the best way to do this?

**Comment by duncs** [comment]
CPANM has always worked for me in the past. What error or problems do you have?

Duncs

**Comment by da0ist** [comment]
--> Working on XML::SAX::Expat
Fetching http://www.cpan.org/authors/id/B/BJ/BJOERN/XML-SAX-Expat-0.51.tar.gz ... OK
Configuring XML-SAX-Expat-0.51 ... OK
==> Found dependencies: XML::Parser
--> Working on XML::Parser
Fetching http://www.cpan.org/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz ... OK
Configuring XML-Parser-2.46 ... N/A
! Configure failed for XML-Parser-2.46. See /home/jeward/.cpanm/work/1594329163.14317/build.log for details.
! Installing the dependencies failed: Module 'XML::Parser' is not installed
! Bailing out the installation for XML-SAX-Expat-0.51.
! Installing the dependencies failed: Module 'XML::SAX::Expat' is not installed
! Bailing out the installation for XML-Simple-2.25.
! Installing the dependencies failed: Module 'Tk::LabEntry' is not installed, Module 'X11::Protocol::Constants' is not installed, Module 'Tk::Dialog' is not installed, Module 'Tk' is not installed, Module 'Tk::Xlib' is not installed, Module 'X11::Protocol::WM' is not installed, Module 'X11::Protocol' is not installed, Module 'XML::Simple' is not installed, Module 'Tk::ROText' is not installed, Module 'X11::Keysyms' is not installed
! Bailing out the installation for App-ClusterSSH-4.16.
16 distributions installed
[jeward@srx-golden-c8p7 ~]$ cpanm App::ClusterSSH # was the command

**Comment by andrew-stevenson-sociomantic** [comment]
This is a failure installing XML::Parser rather than ClusterSSH. Have a look at `/home/jeward/.cpanm/work/1594329163.14317/build.log` to see what went wrong and try to resolve the issue, maybe with the help of the XML::Parser folks. Once you can successfully install XML::Parser then try ClusterSSH again.
