### ISSUE TITLE
Clicking on Menu shows SetupSysMenu: GetSystemMenu() failed for HWND

### ISSUE THREAD

**Issue by sanjay92-gupta** [duncs/clusterssh#128]
Each time menu click , I see following in console window. It does not causes any issues but annoying 

SetupSysMenu: GetSystemMenu() failed for HWND 0xf0644
SetupSysMenu: GetSystemMenu() failed for HWND 0x100644

**Comment by duncs** [comment]
Please upgrade to the latest release (4.15) and try again.

If it fails, please provide a full debug log
