### ISSUE TITLE
how to use other terminal than xterm

### ISSUE THREAD

**Issue by sanjay92-gupta** [duncs/clusterssh#130]
when I launch csshx, it opens up xterm terminal but I want to use other terminal like mintty in cygwin

I have changed following line in config file

terminal=/usr/bin/xterm
to
terminal=/usr/bin/mintty
but that does not work
I get error like and no terminal opens up
Unknown option '-b'
Try '--help' for more information
Unknown option '-b'
Try '--help' for more information
Unknown option '-b'

Thanks

**Comment by pevik** [comment]
Hi,

> when I launch csshx, it opens up xterm terminal but I want to use other terminal like mintty in cygwin

> I have changed following line in config file

> terminal=/usr/bin/xterm
> to
> terminal=/usr/bin/mintty
> but that does not work
> I get error like and no terminal opens up
> Unknown option '-b'
> Try '--help' for more information
> Unknown option '-b'
> Try '--help' for more information
> Unknown option '-b'

Hm, I have no '-b' in ~/.clusterssh/config,
but I guess you have it there. Just comment it out.

Kind regards,
Petr

**Comment by sanjay92-gupta** [comment]
Thanks Petr,
But I don't have any where -b option in my config file

$ cat config
#auto_close=5
#auto_quit=yes
auto_wm_decoration_offsets=no
#cols=-1
#command=
#comms=ssh
#console=console
#console_args=
console_position=+0+0
#external_cluster_command=
#external_command_mode=0600
#external_command_pipe=
#extra_cluster_file=
#extra_tag_file=
#fillscreen=no
#hide_menu=0
history_height=10
#history_width=40
#key_addhost=Control-Shift-plus
#key_clientname=Alt-n
#key_history=Alt-h
#key_localname=Alt-l
#key_macros_enable=Alt-p
#key_paste=Control-v
#key_quit=Alt-q
#key_retilehosts=Alt-r
#key_username=Alt-u
#lang=en
#macro_hostname=%h
#macro_newline=%n
#macro_servername=%s
#macro_username=%u
#macro_version=%v
#macros_enabled=yes
#max_addhost_menu_cluster_items=6
#max_host_menu_items=30
#menu_host_autotearoff=0
#menu_send_autotearoff=0
#mouse_paste=Button-2
#rows=-1
#rsh=rsh
#rsh_args=
screen_reserve_bottom=20
screen_reserve_left=5
screen_reserve_right=5
screen_reserve_top=30
#sftp=sftp
#sftp_args=
show_history=0
#ssh=ssh
#ssh_args=
#telnet=telnet
#telnet_args=
terminal=/usr/bin/xterm
terminal_allow_send_events=-xrm '*.VT100.allowSendEvents:true'
#terminal_args=
#terminal_bg_style=dark
#terminal_colorize=1
#terminal_decoration_height=10
#terminal_decoration_width=8
terminal_font=6x13
terminal_reserve_bottom=10
terminal_reserve_left=5
terminal_reserve_right=5
terminal_reserve_top=20
terminal_size=80x20
#terminal_title_opt=-T
title=CSSH
unique_servers=0
#unmap_on_redraw=no
#use_all_a_records=0
#use_hotkeys=yes
#use_natural_sort=0
#user=
window_tiling=yes
#window_tiling_direction=right

 ~/.clusterssh
$

**Comment by sanjay92-gupta** [comment]
I have tried different terminals like konsole , mintty
mintty gives  Unknown option '-b'
konsole outputs some other messages
'Unknown options: b, g, f, g, x, r, m, f, o, n, t
But none of them opens up any terminal so only xterm works fine

**Comment by duncs** [comment]
Terminals have to satisfy specific requirements to be able to be used with cssh - this is because the cssh console needs to be able to send messages (desktop events) into the terminal, such as keystrokes.  Not all terminals allow this.

xterm allows such use by using the X setting `-xrm '*.VT100.allowSendEvents:true` and is one of the very few that does (I opened a number of issue tickets against other terminal to use this standard feature but after many years of waiting they still have not been done).

If you want to use other terminals I suggest you check through your terminal documentation for using the SendEvents configuration and raise it with the terminal author as required.
