### ISSUE TITLE
no support for 4k screens

### ISSUE THREAD

**Issue by bodsch** [duncs/clusterssh#136]
Currently there is - for me - no support for 4k screens.
The TK window is so small that you can hardly see anything.

I have built a hotfix that fixes this for me. But I would appreciate it if there was a general and clean solution.
https://github.com/duncs/clusterssh/blob/6cbec687bdffe009a6ac1820c146527635546133/lib/App/ClusterSSH/Window/Tk.pm#L1281-L1283

```
    $windows{main_window}
        = MainWindow->new( -title => "ClusterSSH", -class => 'cssh', );
    $windows{main_window}->optionAdd('*font', 'Nimbus 14'); # better for 4k displays
    $windows{main_window}->withdraw;    # leave withdrawn until needed
```

Original:
![cssh_without_patch](https://user-images.githubusercontent.com/6715361/95973426-edb28800-0e13-11eb-9a64-a1b63bf80394.png)

with *Nimbus 12*
![cssh_with_patch](https://user-images.githubusercontent.com/6715361/95973465-fd31d100-0e13-11eb-9679-9daf0abc341a.png)

with *Nimbus 14*
![cssh_with_patch_2](https://user-images.githubusercontent.com/6715361/95973496-058a0c00-0e14-11eb-915c-b6a34008f714.png)

**Comment by GerMalaz** [comment]
Thanks for this.

**Comment by sterni1971** [comment]
Great! Should be an option in the config file.
