### ISSUE TITLE
ClusterSSH in RHEL 7 with the Mate desktop core dumps on startup

### ISSUE THREAD

**Issue by PaulJochum** [duncs/clusterssh#16]
# cssh root@host1 
1ebf8b0 is not a hash at /usr/lib64/perl5/vendor_perl/Tk/MainWindow.pm line 53.
Aborted (core dumped)

I just built ClusterSSH on RHEL 7 with the Mate desktop. I have tried ClusterSSH including 4.03_03, and 3.28. Note, if I am running the Gnome desktop (i.e. Gnome Classic), everything works fine. But each time I try to bring up ClusterSSH under Mate, I receive the above error (although the initial hash value changes each time).

**Comment by duncs** [comment]
Problem with Tk not ClusterSSH so closing off.
