### ISSUE TITLE
Lost prerequisite specification with 4.17

### ISSUE THREAD

**Issue by eserte** [duncs/clusterssh#162]
There are no more prereq specs in 4.17. Compare https://metacpan.org/release/DUNCS/App-ClusterSSH-4.17/source/Build.PL#L5 with https://metacpan.org/release/DUNCS/App-ClusterSSH-4.16/source/Build.PL#L5
(Consequently there are a lot of fail reports because of missing prereqs)

**Comment by duncs** [comment]
This was due to a poor release - I was waiting for CPAN to delete 4.17 top then reupload, but this failed, so I released 4.18
