### ISSUE TITLE
App/ClusterSSH/Getopt.pm has no version anymore

### ISSUE THREAD

**Issue by eserte** [duncs/clusterssh#163]
CPAN.pm refuses to install distributions if one of the containing modules has a lower than the previous install or no version at all. This is currently happening with 4.17:
```
allow_installing_module_downgrades: DUNCS/App-ClusterSSH-4.17.tar.gz (called for App::ClusterSSH) contains downgrading module(s) (e.g. 'App/ClusterSSH/Getopt.pm' would downgrade installed '4.16' to 'undef'). Do you want to allow installing it? [yes]
```

**Comment by duncs** [comment]
This was due to a poor release - I was waiting for CPAN to delete 4.17 top then reupload, but this failed, so I released 4.18
