### ISSUE TITLE
cssh crashes on FreeBSD 9.3

### ISSUE THREAD

**Issue by brevius** [duncs/clusterssh#17]
Hi, 
I have following problem when running cssh on FreeBSD 9.3:

> cssh localhost
Assertion failed: (font != NULL), function IA__FcFontRenderPrepare, file fcmatch.c, line 453.
Abort (core dumped)
> cssh -v 
Version: 4.03_03

I found some information that maybe this is related to fontconfig changes (which should be reflected in clusterssh code?)

**Comment by duncs** [comment]
Problem with Tk/X11::Protocol, not ClusterSSH, so closing off
