### ISSUE TITLE
Tunneled hosts

### ISSUE THREAD

**Issue by kalabantas** [duncs/clusterssh#22]
Hello, is there a way to connect to tunneled hosts (by passing the -t option )?
for example 
ssh -t server -Pxxxx -t ssh node1 -Pyyyy

**Comment by duncs** [comment]
Yes there is.

As per the FAQ answer "Using a 'jump off' or proxy server" on https://github.com/duncs/clusterssh/wiki/Frequently-Asked-Questions-%28FAQ%29, you can set up the ssh tunnel configuration in $HOME/.ssh/config.

See ProxyCommand in the ssh_config man page for entries to add to your ~/.ssh/config file

  Duncs

**Comment by kalabantas** [comment]
Thanks for your reply, and work around. This would result in changing the global settings for ssh, or at least for the current user, which is sometimes inconvenient. At least for me, where I have some 10 nodes behind the master node, and has to connect tunneling through that one, while other servers I do a direct connection, without the need for any ssh proxy server.
I hope there would be a new feature enabling us to enter the proxy in cssh for each host.

**Comment by cqexbesd** [comment]
On 01 Feb 2015, at 17:49, kalabantas <notifications@github.com> wrote:

> Thanks for your reply, and work around. This would result in changing the global settings for ssh, or at least for the current user, which is sometimes inconvenient. At least for me, where I have some 10 nodes behind the master node, and has to connect tunneling through that one, while other servers I do a direct connection, without the need for any ssh proxy server.
> I hope there would be a new feature enabling us to enter the proxy in cssh for each host.
> 
Maybe set that up in your ssh config instead?

**Comment by duncs** [comment]
I have always tried to avoid putting features into clusterssh where a better alternative  exists that can be used instead and I think putting the tunnelling config into the users ssh config file for that specific host is a better option than I could implement (I did look at this before some years ago before I found the ssh config options).

From your description, just using tunnelling config in your local config file for the 10 nodes sounds right and I have used this feature before to great effect. 

Duncs
