### ISSUE TITLE
Use a natural sort when sorting host names

### ISSUE THREAD

**Issue by mperry2** [duncs/clusterssh#24]
ClusterSSH connects to hosts in sorted order, but the sort is ASCII-betical. It would be very helpful if the sort was in natural order.

For servers with names "server1" through "server12", and "SERVER5" in uppercase, I get the following connection and window order:
```
SERVER5
server1
server10
server11
server12
server2
server3
server4
server6
server7
server8
server9
```

Expected result:
```
server1
server2
server3
server4
SERVER5
server6
server7
server8
server9
server10
server11
server12
```

**Comment by mperry2** [comment]
How do I enable this feature? I don't see any changes to the POD in commit ed49237.

**Comment by cqexbesd** [comment]
> On 26.09.2015, at 18:01, Matt Perry <notifications@github.com> wrote:
> 
> How do I enable this feature? I don't see any changes to the POD in commit ed49237.
> 

Set use_natural_sort in you config file. Make sure Sort::Naturally is installed.

Andrew

**Comment by duncs** [comment]
I have updated the docs for this feature

Thanks

Duncs
