### ISSUE TITLE
How to keep alive connections ?

### ISSUE THREAD

**Issue by wichtounet** [duncs/clusterssh#26]
Hello, 

I'm using cssh to manage several machines on which I run long-running algorithms. Often, my connections are disconnected after some time of inaction. If something went wrong, I need to be able to check it in the current connection. Is there anyway to handle longer keep alive ? 

Thanks

**Comment by cqexbesd** [comment]
There could be a number of things timing out your connections - but none are really the responsibility of cssh.

If it's a network device then you might like to try something like ``ServerAliveInterval 240`` in your ssh config file.

**Comment by wichtounet** [comment]
That is weird because I already have ```ServerAliveInterval 120``` in my .ssh/config. If there nothing to configure on cssh, I'll try to investigate the matter on another places.
