### ISSUE TITLE
How can assign log file for all cluster Terminals

### ISSUE THREAD

**Issue by morfeokmg** [duncs/clusterssh#30]
Can I assign one log file for my all cluster terminals?
How can do it?

Thanks in advance.

**Comment by duncs** [comment]
Can you explain to me what your end goal is - what are you trying to achieve?  Do you want all input/output to a terminal logged to a file (such as you might use 'script' for) or something else?



  Duncs

**Comment by duncs** [comment]
No resonse to question so closing.
