### ISSUE TITLE
Docs could refer to vcssh as a downstream utility

### ISSUE THREAD

**Issue by purpleidea** [duncs/clusterssh#32]
FWIW, I wrote a wrapper that glues cssh into vagrant. It is located here: https://github.com/purpleidea/oh-my-vagrant/blob/master/extras/vagrant.bashrc#L88

Feel free to mention it in your docs if you have some!
I didn't know how better to notify your community than to open this issue ticket.

Cheers!
James

**Comment by duncs** [comment]
Added note to FAQ at https://github.com/duncs/clusterssh/wiki/Frequently-Asked-Questions-%28FAQ%29
