### ISSUE TITLE
ClusterSSH startup woes

### ISSUE THREAD

**Issue by tkummell** [duncs/clusterssh#33]
I just installed ClusterSSH and fired it up.  The OS is CentOS 6.6 and the  perl version id 5.10.1.  
Here is the final few messages with --debug set to a value of 4
Any ideas?
TIA
Terry

Resolving cluster names: completed
create_windows: started
REAPER currently returns: -1
Running tags through external command
External command:
Args -L
Running  -L
Command value =  -L
Result:
Return code: 72057594037927935
Exiting via normal routine
Exiting via normal routine
Exiting via normal routine
Exiting via normal routine
Exiting via normal routine
Exiting via normal routine
Exiting via normal routine

**Comment by cqexbesd** [comment]
> On 27.04.2015, at 20:34, tkummell <notifications@github.com> wrote:
> 
> I just installed ClusterSSH and fired it up. The OS is CentOS 6.6 and the  perl version id 5.10.1.
> 
Which version of ClusterSSH?

Thanks

Andrew

**Comment by duncs** [comment]
-L is used to list known 'tags' that are taken out of the configuration files.

If this is a new installation and you have not set up any configuration files, there will be no tags to output.

  Duncs
