### ISSUE TITLE
Can't locate object method "options" via package "App::ClusterSSH::Getopt"

### ISSUE THREAD

**Issue by svetlemodry** [duncs/clusterssh#35]
After building the latest release App-ClusterSSH-4.03_06 on up-to-date Arch Linux system, ccon and ctel ends with the same message:

```bash
 ~]$ ccon --version
Version: 4.03_06
 ~]$ ccon 
Can't locate object method "options" via package "App::ClusterSSH::Getopt" at /usr/share/perl5/vendor_perl/App/ClusterSSH.pm line 1943.
```
which seems not to be the expected behavior.

Package details can be found here: [clusterssh in testing repo](https://www.archlinux.org/packages/community-testing/any/clusterssh/)

And a link to the [PKGBUILD](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/clusterssh) instruction.

Regards.

**Comment by duncs** [comment]
Problem tracked down and fixed - will be released in 4.03_07 

Thanks for the report

  Duncs
