### ISSUE TITLE
Using cssh kills plasma 5 desktop mouse aided hostkeys

### ISSUE THREAD

**Issue by exi** [duncs/clusterssh#36]
After launching cssh, a number of hotkeys stop working in my plasma 5 desktop.
Things like Alt+mouse drag do drag windows or Alt + right mouse button drag to resize windows does not work anymore after starting cssh.

**Comment by exi** [comment]
I just realized, it also kills Alt+Tab for me

**Comment by fusselkater** [comment]
I've opened an issue in kde bug tracker, as i cannot move windows after using clusterssh and i thought this was a kwin bug. I think this is related to this bug here. 
https://bugs.kde.org/show_bug.cgi?id=348569

**Comment by haydnnewport** [comment]
This appears to be the same issue as in #46 and is likely resolved by the same patch
