### ISSUE TITLE
Unable to parse hostname from ""

### ISSUE THREAD

**Issue by kabads** [duncs/clusterssh#37]
Running linux arch here and cssh has run succesfully for over a year - however a recent update must mean that something has changed in the /etc/clusters file, as I'm getting the error once I run. I've edited down my /etc/clusters to be as simple as possible (with only one server to simplify the issue) and it looks like this: 
clusters = ubuntu
ubuntu = my.server.here

then running it, I get: 

[adam@hark .clusterssh]$ cssh -l adam ubuntu
Opening to: = my.server.here
Unable to parse hostname from ""

Any ideas?

**Comment by ffroehling** [comment]
I had the same issue with the exact same configuration. running arch and successfully used cssh for years. Today i found the solution.

The old /etc/clusters file had a syntax like this:

clusters = someCluster
someCluster = host1 host2

With new version of ClusterSSH the config file is simplified. Now it has to be like this:

someCluster host1 host2

You dont need the line "clusters = someCluster ..." anymore. Just comment this out.
Even the "=" in the clusterconfig line is not needed anymore. Just type the name of the cluster followed by the hosts.


Hopefully that helps ;)

**Comment by kabads** [comment]
That does help indeed - many thanks for this. It worked instantly. Perhaps I should rely less on my distro wiki/pages and look at the main website more :-)

**Comment by duncs** [comment]
Nothing to fix so closing ticket.

  Duncs
