### ISSUE TITLE
Cygwin installation issues

### ISSUE THREAD

**Issue by towster** [duncs/clusterssh#39]
Installation on cygwin
followed these instructions basically http://lifeofageekadmin.com/how-to-install-clusterssh-on-cygwin/
Using version 4.03_06

I had a few issues. I got past everything but these are the problems I had.
  1.  Build installdeps did not install Pod::Coverage and Test::Pod::Coverage
  2.  In 30cluster.t there was a test for reading file "cannot_read". I had to disable this.
  3.  Not sure if this last one is my fault or not. I had to add pod2htmd.tmp and pod2htmi.tmp to MANIFEST.SKIP

**Comment by duncs** [comment]
I believe all of these have been addressed recently.  If you have any issues with a more recent version please let me know.

  Duncs
