### ISSUE TITLE
SourceForge bug tracker link in metadata 404

### ISSUE THREAD

**Issue by kentfredric** [duncs/clusterssh#41]
As per: https://metacpan.org/release/DUNCS/App-ClusterSSH-4.03_06 

Issue tracker refers to http://sourceforge.net/tracker/?group_id=89139

This URL redirects to https://sourceforge.net/p/legacy_/tracker/?group_id=89139

And then throws a 404

I would however be completely complacent with the bug tracker moving to github =). SourceForge is not the respected protector of OpenSource it once was.

**Comment by duncs** [comment]
Thanks for the bug report - change made and committed.

I am slowly moving away from sf.net in preference to github, but I haven't moved all the docs yet...

  Duncs
