### ISSUE TITLE
problem in 4.04

### ISSUE THREAD

**Issue by Mikki-black** [duncs/clusterssh#47]
When I upgraded from 4.02 to 4.04(on arch) I got the following error:
Can't locate object method "options" via package "App::ClusterSSH::Getopt" at /usr/share/perl5/vendor_perl/App/ClusterSSH.pm line 1988.

        else {
            $self->config->{ssh_args} = $self->options->options
                if ( $self->options->options );

Commenting these 2 lines  at 1988/1989 makes it work again but I'm not sure what it does. My perl skills are not good enough :(.

**Comment by svetlemodry** [comment]
What if you try to install this package [perl-getopt-argvfile](https://www.archlinux.org/packages/community/any/perl-getopt-argvfile/), still the same error? Might be that it's required as dependency.

**Comment by duncs** [comment]
I am investigating this. Something isn't quite right

Duncs

**Comment by duncs** [comment]
"Can't locate object method "options" via package "App::ClusterSSH::Getopt" at /usr/share/perl5/vendor_perl/App/ClusterSSH.pm line 1988."

Is this the only error you get or are there more?  'options' is a generated method that gets created without issue on my system

**Comment by duncs** [comment]
No response so closing ticket

**Comment by carlo4002** [comment]
Hi, I have the same error.

user@localhost:~$ cssh 
Can't locate object method "options" via package "App::ClusterSSH::Getopt" at /usr/local/share/perl/5.14.2/App/ClusterSSH.pm line 2061.

user@localhost:~$ cssh -v
Version: 4.09
