### ISSUE TITLE
key_quit default of Control-q

### ISSUE THREAD

**Issue by tmancill** [duncs/clusterssh#50]
Hi - as the Debian package maintainer for clusterssh, I'm forwarding a bug report regarding have Control-q as the default for key_quit.  At least one user has been caught off-guard by this, after using Control-s to pause terminal output, that user was unable to resume.

I'm considering patching the Debian packaging to either use a different key combination for key_quit, or to not configure it by default, but thought that I would bring up the question here.  The Debian bug report is [#805868](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805868).

Thank you for considering it.

**Comment by duncs** [comment]
Hey Tony, its been a while :)

I'm happy to change that key - as far as I have so far found, 'Alt-q' seems a reasonable choice unless you have any issues with that?

As a point of note, 'Control-q' has always been the key-quit option, right back to series 3, possibly even series 2.

**Comment by tmancill** [comment]
On 11/26/2015 12:49 AM, Duncan Ferguson wrote:
> Hey Tony, its been a while :)

Indeed - thank you for all of the quality releases.

> I'm happy to change that key - as far as I have so far found, 'Alt-q'
> seems a reasonable choice unless you have any issues with that?

I am not aware of any issues with Alt-q.

> As a point of note, 'Control-q' has always been the key-quit option,
> right back to series 3, possibly even series 2.

I thought it had been that way for a while.

Cheers,
tony

**Comment by duncs** [comment]
I have one more issue to look into before i make the next release

  Duncs
