### ISSUE TITLE
Unknown configuration parameters: extra_tag_file

### ISSUE THREAD

**Issue by waja** [duncs/clusterssh#51]
Accordingly to the manpage, there is an ```extra_tag_file``` configure option in the config file. Unfortunately this seems not to work actually:

```
$ cssh -v
Version: 4.03_06
$ cssh foo
Unknown configuration parameters: extra_tag_file
$ grep extra_tag_file ~/.clusterssh/config 
extra_tag_file = /home/waja/.clusterssh/tags
$ man cssh | grep -1 extra_tag_file
           Extra tag files may be specified either as an option (see "tag-file") or within the user's
           $HOME/.clusterssh/config file (see "extra_tag_file" configuration option).
```

Many thanks for looking into it.

**Comment by waja** [comment]
@duncs Do you need any further information? Something I need to provide? Is this a bug or maybe a fault on my side?

**Comment by duncs** [comment]
I have enough information. What I don't have enough of currently is time. I will look into this when I can

Duncs

**Comment by waja** [comment]
> I have enough information. What I don't have enough of currently is time. I will look into this when I can

Thanks @duncs. Don't worry. Just wanted to know if there is anything I can do.

**Comment by duncs** [comment]
This has been fixed and pushed to the git repository.  It will be included in the next release.

  Duncs

**Comment by waja** [comment]
Many thanks!
