### ISSUE TITLE
How to define name ranges in the "clusters" configuration file.

### ISSUE THREAD

**Issue by lserena1** [duncs/clusterssh#53]
Hi Duncan, 

If I type this from the command line:
cssh devstack0{1..5} &
it works as expected, i.e. it opens 5 xterm sessions to devstack01, 02, 03, 04 and 05.

But if I put something simlar in ~/.clusterssh/clusters 

devstack    devstack0{1..5}

When I run
cssh devstack 
from the prompt, all I get is:
Opening to: devstack0{1..5}
Unable to parse hostname from "devstack0{1..5}"
$

What is the correct way to define a name range in the clusters file?

Thanks in advance

Loris

**Comment by duncs** [comment]
I have got this working with commas, but not in ranges

e.g. this works okay
    devstack devstack{1,2,3,4,5}

but this doesnt yet
     devstack devstack0{1..5}

I am considering how best to do this.

The changes I am making are not yet in the repo.

  Duncs

**Comment by lserena1** [comment]
Thank you for looking into this

**Comment by duncs** [comment]
Code changes have been pushed to the repo.  Let me know if you find any issues

  Duncs
