### ISSUE TITLE
CSSH terminal logging

### ISSUE THREAD

**Issue by Solace50** [duncs/clusterssh#64]
Hey is it currently possible to log the output of your terminal sessions when using CSSH? What would be the arguments used? I cannot find anything in the documentation.

**Comment by cqexbesd** [comment]
> Hey is it currently possible to log the output of your terminal sessions when using CSSH? What would be the arguments used? I cannot find anything in the documentation.
> 
Im not aware of cssh having support - it doesn't even see the terminal output. You can probably do it using facilities in whatever terminal emulator you use - or maybe use "script" as your command.

**Comment by duncs** [comment]
There is command logging, whereby all commands typed into the console is recorded, but that is as much logging as is feasible to include.

As @cqexbesd suggested, you are best using a command such as 'script' to record each terminal session on each server:

`cssh -a "script /tmp/%s" hostA hostA hostB hostB`

I could possibly add in some more macros if this would be useful, such as %d for some kind of date/time/timestamp macro.

  Duncs
