### ISSUE TITLE
Is the official repo on GitHub (this one) or on SourceForge?

### ISSUE THREAD

**Issue by CristianCantoro** [duncs/clusterssh#65]
Hi,

If I look at the repo [here on GitHub](https://github.com/duncs/clusterssh) in the header there a link to the [Cluster SSH project on SourceForge](https://sourceforge.net/projects/clusterssh/). However, the [`README`](https://github.com/duncs/clusterssh/blob/master/README) says that the website is GitHub and points to GitHub for code and issues. At the same time, the SourceForge project list as project website the [wiki here on GitHub](https://github.com/duncs/clusterssh/wiki). Finally if I look at the [releases on GitHub](https://github.com/duncs/clusterssh/releases) and [on SourceForge](https://sourceforge.net/projects/clusterssh/files/2.%20ClusterSSH%20Series%204/) they are respectively `v. 4.03_03` (Sept 2014) and `v. 4.07` (Apr 2016)¸ so it seems that the most up-to-date release is available through SourceForge.

This situation is a little bit confusing.

Maybe is worth specifying in the README:
*  which repo is "official" and which is a "mirror";
* where people should go for getting the most up-to-date release;

Thanks!

**Comment by duncs** [comment]
Github is teh correct place - I am slowly moving away from SourceForge.

I'll update the appropriate places to make this clearer.

Thanks for the report.

**Comment by duncs** [comment]
https://github.com/duncs/clusterssh/wiki updated
https://github.com/duncs/clusterssh updated

I need to look into the releases to find out why they are no longer being picked up by GitHub correctly.

**Comment by duncs** [comment]
Release tags updated.
