### ISSUE TITLE
version 4.08 thinks screen is larger than it is

### ISSUE THREAD

**Issue by rlucassen2** [duncs/clusterssh#71]
xrandr | grep '*'
   1366x768      60.06*+  40.04  

When starting 13 ssh sessions, the 13th is under the bottom of the screen. When using 6 xterms I need to adjust screen_reserve_bottom=60 (default) to 100. Four screens is no problem. It seems that I need to adjust screen_reserve_bottom for every number of xterms.

Downgrade to 4.07 resolves the problem.

Debian testing, Windowmaker

**Comment by rlucassen2** [comment]
I'm not the only one:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842965

R.

**Comment by duncs** [comment]
I have asked Tony for his patch so I can apply it to the repository.

  Duncs

**Comment by duncs** [comment]
The patch has now been applied to the repo, so the new algorithm is configurable (defaults to original method).
