### ISSUE TITLE
user lost on "re-add closed sessions"

### ISSUE THREAD

**Issue by harridu** [duncs/clusterssh#72]
If I run "cssh user@{cecil,porky,sylvester}", close porky and select "re-add closed sessions", then the "user@" has been lost for porky.
This is clusterssh 4.08, as included in Debian.

**Comment by duncs** [comment]
Confirmed this is a bug.    I will investigate.

**Comment by duncs** [comment]
Fix - will be released in version 4.09 - was due to using the wrong session attribute to reopen the new session
