### ISSUE TITLE
Cannot ssh with ssl key file

### ISSUE THREAD

**Issue by kalkir** [duncs/clusterssh#73]
I am trying to login with SSH key, but I couldn't find any option with ssh_args. how can I login with key authentication?

**Comment by cqexbesd** [comment]
The easiest way (IMO) is to set up the ssh-agent as you would for normal SSH. Then the SSHs spawned by cssh will just use it without requiring any changes.

**Comment by kalkir** [comment]
I have configured ssh-agent, but still cannot connect with the key

**Comment by kalkir** [comment]
Sorry, it's working. Thanks,
