### ISSUE TITLE
.ssh/config Include directive is ignored

### ISSUE THREAD

**Issue by Azenet** [duncs/clusterssh#77]
Hi,

The `Include` directive in `.ssh/config` is ignored, and for me that causes massive delay starting ClusterSSH, since it tries to lookup the hostname for each host.
I put [this](https://github.com/Azenet/clusterssh/commit/f9c6120477b52d9fd0248ec909497ba8347dee5e) together for my own use, but it's probably bad Perl code.

**Comment by duncs** [comment]
It looks fine to me.  The only thing I can see is to change line 40 from
```read_ssh_file($self, $self->{ssh_config});```
to
```$self->read_ssh_file($self->{ssh_config});```

Can you put it through as a pull request, please?
