### ISSUE TITLE
Can't locate object method "options" via package "App::ClusterSSH::Getopt"

### ISSUE THREAD

**Issue by carlo4002** [duncs/clusterssh#79]
Hello, I upgrade my machine ubuntu and I got this error

user@localhost:~$ cssh
Can't locate object method "options" via package "App::ClusterSSH::Getopt" at /usr/local/share/perl/5.14.2/App/ClusterSSH.pm line 2061.

user@localhost:~$ cssh -v
Version: 4.09

Commenting those lines fix the problem but I dont think it is right

**Comment by duncs** [comment]
I am not able to reproduce this - if this is sstill a problem for you can you show the area of code this is happening for you in (lines 2056 to 2064) and also provide your ~/.clusterssh/config file?

**Comment by duncs** [comment]
Please retry with the latest version (4.15) and if it still fails upload a full debug log.
