### ISSUE TITLE
Paste text to consoles

### ISSUE THREAD

**Issue by JonnyTech** [duncs/clusterssh#80]
Is it possible to paste text from the clipboard into the cssh consoles? (I have a rather long an complicated password that I would rather not type in.) I am on Debian and the usual keyboard combination of CTRL+SHIFT+V does not work.

**Comment by duncs** [comment]
CTRL-V should be enough as the console is a normal X window, not a terminal. Also pasting with the middle or right click (depending on your wm) should work

Duncs

**Comment by JonnyTech** [comment]
Thanks, but none of those options worked - I should have said that I tried those first.

X documentation states add `*selectToClipboard: true` to the /etc/X11/app-defaults/XTerm file. 

After that, I can restart ClusterSSH and paste with CTRL+V

Cheers for the X pointer - maybe this should be added to the FAQ.

**Comment by duncs** [comment]
Thanks for the info - FAQ entry duncs/clusterssh added
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
duncs/clusterssh
 clusterssh - Cluster SSH - Cluster Admin Via SSH  |   |

  |

  |

 
 

    On Tuesday, 28 March 2017, 19:03, JonnyTech <notifications@github.com> wrote:
 

 Thanks, but none of those options worked - I should have said that I tried those first.X documentation states add *selectToClipboard: true to the /etc/X11/app-defaults/XTerm file.After that, I can restart ClusterSSH and paste with CTRL+VCheers for the X pointer - maybe this should be added to the FAQ.—
