### ISSUE TITLE
Should Not Tile Across Multiple Monitors

### ISSUE THREAD

**Issue by stone212** [duncs/clusterssh#82]
Currently cssh tiling happens across multiple monitors.  This is bad because:

1) I only want to have my xterms on one monitor

2) The way it handles tiling assumes that both monitors are the same height.  Since they are not, the spillover shows me only half of the terminals on the second monitor.

Thank you.

**Comment by duncs** [comment]
This is a known issue - #68 

Closing this one as a duplicate.

  Duncs
