### ISSUE TITLE
Unable to parse hostname from ""

### ISSUE THREAD

**Issue by stone212** [duncs/clusterssh#84]
I have a .clusterssh/clusters file that reads:

`vpns = root@vpn1:21 root@vpn2:21 root@vpn3:21`

/etc/hosts defines vpn1, vpn2, and vpn3.  I can ping them by these hostnames

I type the following command:

`cssh vpns`

and I get the following feedback:

`Opening to: = root@vpn1:21 root@vpn2:21 root@vpn3:21`
`Unable to parse hostname from ""`

**Comment by cqexbesd** [comment]
You don't need the = character.

**Comment by stone212** [comment]
Got it.  Every page I had read on the subject said I did, but now that you're reorganized the docs I tried it and it worked.  I actually just came here to close the ticket, which you've already done.

Thank you!
