### ISSUE TITLE
Range expansion issue

### ISSUE THREAD

**Issue by pemazzon** [duncs/clusterssh#89]
I have various clusters defined like

tag  server-01 server-02 server-03...

server name contains the dash sign '-'. If I define 

tag  server-0{1..N}

range expansion doesn't work although 'sub expand' in Range.pm seems to work fine. Any line defined like

tag  server{1..N}

works. Just the dash seems to be the problem.

**Comment by duncs** [comment]
Fixed in the repo - it was a simple code change to allow dashes to be handled correctly in the expand sub.
