### ISSUE TITLE
Wrong bugtracker in module documentation

### ISSUE THREAD

**Issue by pink-mist** [duncs/clusterssh#92]
The documentation for the module at https://metacpan.org/pod/App::ClusterSSH#BUGS lists an email address at rt.cpan.org as the correct place for reporting bugs for ClusterSSH. And the following section https://metacpan.org/pod/App::ClusterSSH#SUPPORT also suggests checking rt.cpan.org for the bug/request tracker, but when you visit it, it tells us that this github issue tracker is the right place to report bugs.

**Comment by duncs** [comment]
Thanks for the report - fixed in the repository

  Duncs
