### ISSUE TITLE
There is not any appdata.xml/metainfo.xml file available in the ClusterSSH

### ISSUE THREAD

**Issue by rosset** [duncs/clusterssh#94]
There is not any appdata.xml/metainfo.xml file available in the ClusterSSH package. Because of this, ClusterSSH cannot be found and/or installed using the
GNOME Software application or another package manager UI based on AppStream.

Steps to Reproduce:

1. Open GNOME Software.
2. Type "clusterssh".

Original bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1476485

**Comment by duncs** [comment]
I do not believe this should be fixed at source - this appears to be a Fedora issue with RPM packaging of ClusterSSH, rather than an issue with ClusterSSH itself

  Duncs
