### ISSUE TITLE
cssh start up issue

### ISSUE THREAD

**Issue by zabbix112** [duncs/clusterssh#96]
Good Afternoon,

So I have used Clusterssh in the past, different company and now Im at a new one that I can use it again but I am running in to a new issue.
(standard info)
VM
Centos 7.4.1708 
xterm-295-3.el7.x86_64
.csshrc "is the file Im using"

I type in cssh "My Cluster" see below for exact typing. 

[root@example-server ~]# cssh group1
Moved $HOME/.csshrc to $HOME/.csshrc.DISABLED

**Comment by cqexbesd** [comment]
Now days clusterssh uses ~/.clusterssh/config for configuration. Check out the README or man page for documentation.

**Comment by zabbix112** [comment]
Thank you 

oddly enough I started to do digging on the system and found the location. I love this application, I would help support it but perl is not my strong programming language.
