### ISSUE TITLE
Multiple ranges no longer working

### ISSUE THREAD

**Issue by lazyfrosch** [duncs/clusterssh#97]
Cluster Example:

    test icinga{a,b}-test{1,2}

Error:

    Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\{a,b}-test{ <-- HERE 1,2\}/ at /usr/share/perl5/App/ClusterSSH/Range.pm line 84.

This worked without a problem before. I'm on `4.10_02` on Debian testing (buster)

**Comment by lazyfrosch** [comment]
My quick fix: Make the RegExp non-greedy

```diff
--- /usr/share/perl5/App/ClusterSSH/Range.pm.orig	2017-11-17 15:36:50.900955097 +0100
+++ /usr/share/perl5/App/ClusterSSH/Range.pm	2017-11-17 15:36:55.908944004 +0100
@@ -68,7 +68,7 @@
             next;
         }
 
-        my ( $base, $spec ) = $item =~ m/^(.*?\{(.*)\}.*?)$/;
+        my ( $base, $spec ) = $item =~ m/^(.*?\{(.*?)\}.*?)$/;
 
         for my $section ( split( /,/, $spec ) ) {
             my ( $start, $end );
```

**Comment by lazyfrosch** [comment]
Oh btw. it works with single patterns:

    test icinga-test{2,3}

**Comment by duncs** [comment]
Thanks for the report and the fix - this has been pushed to the git repo
